### ISSUE TITLE
Building from source on Amazon Linux for ARM does not work after rel 1.0.20

### ISSUE THREAD

**Issue by davidecoccia** [akopytov/sysbench#505]
Building with rel 1.0.20 works fine
When Building with master I get the following error

```
sh-5.2$ make -j
Making all in third_party/luajit
make[1]: Entering directory '/home/ssm-user/sysbench/third_party/luajit'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ssm-user/sysbench/third_party/luajit'
Making all in third_party/concurrency_kit
make[1]: Entering directory '/home/ssm-user/sysbench/third_party/concurrency_kit'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ssm-user/sysbench/third_party/concurrency_kit'
Making all in src
make[1]: Entering directory '/home/ssm-user/sysbench/src'
Making all in drivers
make[2]: Entering directory '/home/ssm-user/sysbench/src/drivers'
Making all in mysql
make[3]: Entering directory '/home/ssm-user/sysbench/src/drivers/mysql'
gcc -DHAVE_CONFIG_H -I. -I../../../config  -I/usr/include/mysql -I/usr/include/mysql/mysql -I../../../src -I/home/ssm-user/sysbench/third_party/luajit/inc -I/home/ssm-user/sysbench/third_party/concurrency_kit/include -D_GNU_SOURCE  -DCK_MD_CACHELINE=128 -Wall -Wextra -Wpointer-arith -Wbad-function-cast -Wstrict-prototypes -Wnested-externs -Wno-format-zero-length -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wcast-align -Wvla    -O3 -funroll-loops -ggdb3  -MT libsbmysql_a-drv_mysql.o -MD -MP -MF .deps/libsbmysql_a-drv_mysql.Tpo -c -o libsbmysql_a-drv_mysql.o `test -f 'drv_mysql.c' || echo './'`drv_mysql.c
drv_mysql.c: In function ‘mysql_drv_real_connect’:
drv_mysql.c:420:24: error: ‘MYSQL_OPT_COMPRESSION_ALGORITHMS’ undeclared (first use in this function)
  420 |     mysql_options(con, MYSQL_OPT_COMPRESSION_ALGORITHMS, args.compression_alg);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drv_mysql.c:420:24: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [Makefile:440: libsbmysql_a-drv_mysql.o] Error 1
make[3]: Leaving directory '/home/ssm-user/sysbench/src/drivers/mysql'
make[2]: *** [Makefile:412: all-recursive] Error 1
make[2]: Leaving directory '/home/ssm-user/sysbench/src/drivers'
make[1]: *** [Makefile:591: all-recursive] Error 1
make[1]: Leaving directory '/home/ssm-user/sysbench/src'
make: *** [Makefile:481: all-recursive] Error 1
```

uname -r: 6.1.34-59.116.amzn2023.aarch64

**Comment by davidecoccia** [comment]
@dveeden I think this can be related to https://github.com/akopytov/sysbench/commit/5f669c98eb062e1e27c98aa98cfb022c2c483391

**Comment by dveeden** [comment]
@davidecoccia what MySQL version are you compiling against?

**Comment by davidecoccia** [comment]
@dveeden I am installing the package "mariadb105-devel" which works with MySQL 8.0.32 until sysbench release 1.0.20

**Comment by wsm12138** [comment]
you can checkout 4228c85ff9164aac93eb7af5ed8a622b039e3c5b to skip this error

**Comment by dveeden** [comment]
@davidecoccia Please see the PR and test it if that's possible for you.

**Comment by davidecoccia** [comment]
works fine with https://github.com/akopytov/sysbench/pull/506
👍
