### ISSUE TITLE
1.0.0 clock_gettime runtime failure built with macOS 10.11 and Xcode 8.x

### ISSUE THREAD

**Issue by ilovezfs** [akopytov/sysbench#105]
Full build log is here: https://gist.github.com/ilovezfs/29f7e0f5d7cdcbcf2cd8f290233e3e0b

I encountered this problem while working on the 1.0.0 upgrade from Homebrew.
```
iMac-TMP:~ joe$ brew test -v sysbench
Testing sysbench
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170204-35470-o2ykkh.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sysbench.rb -v --HEAD
==> /usr/local/Cellar/sysbench/HEAD-f964f5b/bin/sysbench --test=cpu --cpu-max-prime=1 run
WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.
sysbench 1.0.0-f964f5b (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Prime numbers limit: 1

Initializing worker threads...

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/sysbench/HEAD-f964f5b/bin/sysbench
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/sysbench/HEAD-f964f5b/bin/sysbench
  Expected in: /usr/lib/libSystem.B.dylib

Error: sysbench: failed
```
This will occur if sysbench 1.0.0 is built on macOS 10.11 El Capitan either without the Command Line Tools (CLT) installed, or with SDKROOT set to the Xcode.app (8.x) SDK (SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk), or both. Note that this is a 10.11 specific problem.

The problem is that the use of clock_gettime in sysbench is enabled if ac_cv_have_decl_clock_gettime is determined to be "yes", so I can work around it by setting
```
    if MacOS.version == :el_capitan && MacOS::Xcode.installed? && MacOS::Xcode.version >= "8.0"
      ENV["ac_cv_have_decl_clock_gettime"] = "no"
    end
```
The Xcode 8 SDK does indeed declare clock_gettime regardless of whether you're using it on 10.11 or 10.12 so a check merely for declaration is inappropriate given that it's only actually implemented on 10.12.

**Comment by akopytov** [comment]
Thank for the report. I don't have 10.11 around, can you please check if the pushed fix works?

By the way, sysbench now implements 'make test' so you may want to use that instead of the custom implementation in Homebrew.

**Comment by ilovezfs** [comment]
Yes, the fix is good. No clock_gettime in the binary on 10.11. Yes clock_gettime in the binary on 10.12.

"make test" is build time, whereas as our test blocks are of the binary bottles after the build environment is gone. We generally try to avoid make test during our builds because too many upstreams expect them to be broken and because they often have long run times.

**Comment by ilovezfs** [comment]
To wit,
```
==> make test
cd tests && /Applications/Xcode.app/Contents/Developer/usr/bin/make test
./test_run.sh
./test_run.sh: line 80: cram: command not found
make[1]: *** [test] Error 127
make: *** [test] Error 2
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make test
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```
So we'd need to get cram from somewhere.

**Comment by akopytov** [comment]
Got it, thanks for verifying the fix.

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by ilovezfs** [comment]
@akopytov BTW, do you mind tagging a 1.0.1 with the fix, or should we backport the commit as a patch to 1.0.0 downstream?

**Comment by akopytov** [comment]
@ilovezfs tagged 1.0.1 with the fix.

**Comment by ilovezfs** [comment]
@akopytov Thank you. Merged! https://github.com/Linuxbrew/homebrew-core/issues/1734

**Comment by ilovezfs** [comment]
@akopytov Thank you. Merged! https://github.com/Homebrew/homebrew-core/pull/9679
