### ISSUE TITLE
sysbench 1.0.9 doesn't build with mariadb 10.2.8

### ISSUE THREAD

**Issue by xavierba** [akopytov/sysbench#172]
mysql_version.h has been moved to server/mysql_version.h in (at least) mariadb 10.2.8.
This prevents sysbench from building. 
Here's an extract of the build log:
`
make[3]: Entering directory '/builddir/build/BUILD/sysbench-1.0.9/src/drivers/mysql'
gcc -DHAVE_CONFIG_H -I. -I../../../config  -I/usr/include/mysql  -I../../../src -I/usr/include/luajit-2.1  -D__x86_64__ -I/usr/include/ck  -D_GNU_SOURCE  -W -Wall -Wextra -Wpointer-arith -Wbad-function-cast   -Wstrict-prototypes -Wnested-externs -Wno-inline -Wno-format-zero-length   -funroll-loops  -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wcast-align        -pthread -O2 -ggdb3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c -o libsbmysql_a-drv_mysql.o `test -f 'drv_mysql.c' || echo './'`drv_mysql.c
make[3]: Leaving directory '/builddir/build/BUILD/sysbench-1.0.9/src/drivers/mysql'
In file included from drv_mysql.c:37:0:
/usr/include/mysql/mysql.h:439:3: warning: function declaration isn't a prototype [-Wstrict-prototypes]
   MYSQL_CLIENT_PLUGIN_HEADER
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/mysql/mysql.h:584:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 my_bool STDCALL mysql_embedded();
 ^~~~~~~
drv_mysql.c:38:10: fatal error: mysql_version.h: No such file or directory
 #include <mysql_version.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:454: libsbmysql_a-drv_mysql.o] Error 1
`

**Comment by akopytov** [comment]
Hm, as I understand, `-I/usr/include/mysql` comes from `mysql_config`. If it does return `-I/usr/include/mysql`, but `mysql_version.h` is installed to `/usr/include/server/`, then I would consider it a MariaDB bug, that should also break lots of other software packages.

Can you double check it's not a MariaDB installation error?

**Comment by xavierba** [comment]
Sorry, I wasn't clear.
Previous path was /usr/include/mysql/mysql_version.h.
Current path is /usr/include/mysql/server/mysql_version.h.

**Comment by akopytov** [comment]
Yes, my question still holds. I corrected a typo in my previous comment.

**Comment by akopytov** [comment]
Nevermind, I installed libmariadb-dev in a docker image with Debian Jessie. `mysql_version.h` is indeed under `/usr/include/mysql/server`.

**Comment by xavierba** [comment]
It seems the behaviour changed with mariadb 10.2.8.
https://github.com/MariaDB/server/commit/3ec96c1824
`
# mysql_config
Usage: /usr/bin/mysql_config-64 [OPTIONS]
Options:
        --cflags         [-I/usr/include/mysql ]
        --include        [-I/usr/include/mysql]
        --libs           [-L/usr/lib64/mysql  -lmariadb -lpthread -lz -ldl -lm -lssl -lcrypto]
        --libs_r         [-L/usr/lib64/mysql  -lmariadb -lpthread -lz -ldl -lm -lssl -lcrypto]
        --plugindir      [/usr/lib64/mysql/plugin]
        --socket         [/var/lib/mysql/mysql.sock]
        --port           [0]
        --version        [10.2.8]
        --libmysqld-libs [-L/usr/lib64/mysql  -lmysqld -lpthread -lz -lm -ldl -lssl -lcrypto -lpcre -lcrypt -laio -lsystemd]
        --variable=VAR   VAR is one of:
                pkgincludedir [/usr/include/mysql]
                pkglibdir     [/usr/lib64/mysql]
                plugindir     [/usr/lib64/mysql/plugin]
`

**Comment by akopytov** [comment]
I posted a question for MariaDB engineers, since I don't see an easy way to fix this: https://jira.mariadb.org/browse/MDEV-13370?focusedCommentId=100190&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-100190

**Comment by akopytov** [comment]
A fix based on the discussion in https://jira.mariadb.org/browse/MDEV-13773 has been pushed to both 1.0 and master. I have tested it with MariaDB 10.2.8 in Fedora Rawhide.

**Comment by hydrapolic** [comment]
Just tested that patch with sysbench 1.0.9 on Linux Gentoo with both Mariadb 10.1 and Mariadb 10.2, it compiles fine. Thanks @akopytov
